filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/replay/*.log
    fields:
      dataset: bgl_replay
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_stderr: true
